version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
###   Issues with lerna stop us from auto-updating npm dependencies
###   See: https://github.com/codeoverflow-org/nodecg-io/issues/263
# - package-ecosystem: "npm"
#   directory: "/"
#   schedule:
#     interval: "daily"
