version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "monthly"
